site_name: Share Forge

theme:
  name: material
  palette:
    # Light mode (optional; can be toggled off if you want dark-only)
    - scheme: default
      primary: indigo
      accent: cyan
      toggle:
        icon: material/brightness-7  # Icon for light mode
        name: Switch to dark mode
    # Dark mode (default)
    - scheme: slate  # Or 'default' for a slightly warmer dark
      primary: indigo
      accent: cyan
      toggle:
        icon: material/brightness-4  # Icon for dark mode
        name: Switch to light mode
  features:
    - content.code.copy
    - navigation.instant
    - search.suggest
    - search.highlight
    - navigation.sections  # Optional: Collapsible sections